# Generated by Django 5.0.1 on 2024-03-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.DeleteModel(
            name='ActivityType',
        ),
    ]
