# Generated by Django 5.0.1 on 2024-02-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='leaderboard_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
