# Generated by Django 5.0.1 on 2024-03-05 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_active',
        ),
    ]
