# Generated by Django 5.0.1 on 2024-03-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvariant',
            name='item_color',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
