# Generated by Django 5.0.1 on 2024-02-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0002_alter_leaderboard_leaderboard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
