# Generated by Django 5.0.1 on 2024-03-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0002_remove_activity_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
