# Generated by Django 5.0.1 on 2024-04-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0003_alter_item_description_alter_item_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='leaderboard_logo',
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
