# Generated by Django 5.0.1 on 2024-03-05 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0003_activity_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userparticipated',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='userparticipated',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='activity',
            name='participated_users',
            field=models.ManyToManyField(blank=True, related_name='participated_activities', through='engage.UserParticipated', to=settings.AUTH_USER_MODEL),
        ),
    ]
