# Generated by Django 5.0.1 on 2024-02-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0003_alter_activity_end_date_alter_activity_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
