# Generated by Django 5.0.1 on 2024-03-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0004_rename_activity_id_userparticipated_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userparticipated',
            name='date_participated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
