# Generated by Django 5.0.1 on 2024-04-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0004_remove_leaderboard_leaderboard_logo_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='monthly_rank',
            field=models.IntegerField(default=0),
        ),
    ]
