# Generated by Django 5.0.1 on 2024-03-04 00:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage', '0005_remove_itemvariant_item_color_item_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='interested_users',
            field=models.ManyToManyField(related_name='interested_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserInterested',
        ),
    ]
