# Generated by Django 5.0.1 on 2024-04-09 16:51

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintoken',
            name='expiration_date',
            field=models.DateTimeField(default=accounts.models.fifteen_minutes_from_now),
        ),
    ]
