# Generated by Django 5.0.1 on 2024-04-06 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logintoken",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 6, 20, 47, 51, 3284, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
