# Generated by Django 5.0.1 on 2024-02-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lifetime_points',
            field=models.IntegerField(default=0),
        ),
    ]
