# Generated by Django 5.0.1 on 2024-03-10 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_logintoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 0, 5, 24, 371527, tzinfo=datetime.timezone.utc)),
        ),
    ]
