# Generated by Django 5.0.1 on 2024-04-07 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_logintoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 21, 49, 56, 314202, tzinfo=datetime.timezone.utc)),
        ),
    ]
