# Generated by Django 5.0.1 on 2024-03-11 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_logintoken_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logintoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 11, 0, 57, 5, 762786, tzinfo=datetime.timezone.utc)),
        ),
    ]
