# Generated by Django 5.0.1 on 2024-03-13 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_logintoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintoken',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 18, 55, 48, 163651, tzinfo=datetime.timezone.utc)),
        ),
    ]
